# References & Sources {-}


- World Bank Data. (2020). St. Lucia. https://data.worldbank.org/country/st-lucia 
Food and Agriculture Organization of the 

- United Nations.https://www.fao.org/investment-learning-platform/themes-and-tasks/results-based-management/en/#c309481

- Freedom House. (2021). St. Lucia Overview. https://freedomhouse.org/country/st-lucia/freedom-world/2021 

- Freedom House. (2021). St. Lucia Overview. https://freedomhouse.org/country/st-lucia/freedom-world/2021

- Planning of Saint Lucia. https://observatorioplanificacion.cepal.org/en/planning-systems/planning-saint-lucia 

- The Citizen's Guide to the 2021-2022 budget. Ministry of Finance, Economic Growth, Job Creation, External Affairs and the Public Service. Consulted in: https://www.govt.lc/media.govt.lc/www/pressroom/news/attachments/the-citizen-s-guide-to-the-2021-2022-budget.pdf 

- Tolson, R., Niddrie, D. L., & Momsen, J. D. (s. f.). Saint Lucia - History. Encyclopedia Britannica. https://www.britannica.com/place/Saint-Lucia/History 

- United Nations Development Group. Results-Based Management Handbook. https://unsdg.un.org/download/160/246#:~:text=RBM%20is%20a%20management%20strategy,higher%20level%20goals%20or%20impact).

- United Nations Development Programme. Results Based Management. Concepts and Methodology. http://web.undp.org/evaluation/documents/RBMConceptsMethodgyjuly2002.pdf 

The rest of the sources are official websites of the Government of Saint Lucia or regional institutions/initiatives, such as (but not limited only):

- Government of Saint Lucia. https://www.govt.lc/

- Cabinet of Ministers. https://www.govt.lc/cabinet-rejected

- Departments of the Government of Saint Lucia. https://www.govt.lc/departments (and all the microsites located in this page)


