
#	Planning & budgeting process  {#appendixC}

## National budgeting process^[The Citizen's Guide to the 2021-2022 budget. Ministry of Finance, Economic Growth, Job Creation, External Affairs and the Public Service. Consulted in: https://www.govt.lc/media.govt.lc/www/pressroom/news/attachments/the-citizen-s-guide-to-the-2021-2022-budget.pdf ] 

Saint Lucia's budgeting process consists of three main stages: 1. Budget planning and preparation; 2. Finalisation and 3. Budget implementation and monitoring. The stages are comprised as follow.

### Budget planning and preparation

1.	The Ministry of Finance (MOF) prepares the Macroeconomic Outlook for the upcoming fiscal year where macroeconomic indicators are reviewed and projections for recurrent revenue, recurrent expenditure, and capital expenditure are formulated.

2.	A request/call for new initiatives for recurrent revenue, recurrent expenditure as well as capital expenditure are sent to ministries.

3.	The fiscal targets including economic indicators are established to determine revenue and expenditure projections, which aid in establishing overall spending limits for the new fiscal year.

4.	The MOF issues the Estimates Call. In this circular, the preliminary allocations are outlined as well as other requirements of the MOF.

5.	The Minister for Finance invites the private sector to submit inputs for the budget.

6.	The agencies submit their new initiatives. The MOF reviews the submission and prepares recommendations in consultation with agencies.

7.	Technical Budget Committee meetings are held with staff of the MOF and Department of Economic Development and Youth Economy to discuss recommendations, indicators and fiscal targets from the Budget Office, Debt Unit, Research Department and Department of Economic Development and Youth Economy. This committee then formulates recommendations and submits to the Budget Policy committee for approval through several iterations.

### Finalisation

8.	After extensive reviews and dialogue the MOF present the draft estimates to the Minister for Finance.

9.	The Minister and Finance Officials meet with Cabinet to finalise the estimates.

10.	A second call circular is sent to the agencies communicating cabinet final approval of the Budget and changes required to be reflected in the estimates book, and any other relevant instructions.

11.	Following the Cabinet meeting, MOF prepares the printed estimates and develops the budget papers.

12.	The Ministry for Finance prepares and submits a draft appropriation bill to the Attorney General

13.	The Attorney General reviews the Appropriation Bill and prepares the Resolution.

14.	Minister for Finance tables the Resolution in the House of Parliament.

15.	Members of the Lower House debate the Estimates.

16.	The Appropriation Bill is tabled and debated.

17.	When passed the Appropriation Act is then assented to by the Governor-General and Gazetted.
 

### Budget implementation and monitoring

18.	The MOF sends out a call to agencies to submit their expenditure request (recurrent expenditure, capital), revenue (actual and projections), and procurement plans on a quarterly basis.

19.	The MOF releases the allocation to agencies on a quarterly basis. The release of allocation is based in part on the current revenue performance and projections for the year. Capital expenditure allocation is determined based on the availability of the loan, grant, bond, or other fundraising and the status of the projects.

20.	Agencies are required to submit monthly revenue reports and quarterly performance reports to the MOF.

21.	The MOF is also required to produce and submit quarterly performance reports to the Minister for Finance.

